server:
  port: 8061

swagger:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/test/,file:${web.upload-path}

# 文件上传地址
web:
  upload-path: C:\Users\Administrator\Desktop\上传文件\
  file:
    path: C:\Users\Administrator\Desktop\上传文件\

#mybatis.type-aliases-package=com.study.domain
#可以自动识别
#spring.datasource.driver-class-name =com.mysql.jdbc.Driver
#增加打印sql语句，一般用于本地开发测试
#  mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
