server:
  port: 8061

swagger:
  enabled: true

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/test/,file:${web.upload-path}

#文件上传路径配置
web:
  file:
    path: /Users/jack/Desktop/